services:
  - type: web
    name: diamondfinder-backend
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      python postinstall.py
    startCommand: python server_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
      - key: PIP_NO_CACHE_DIR
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "requirements.txt"
        - "runtime.txt"
        - "enriched_servers.json" 