services:
  - type: web
    name: diamondfinder-backend
    env: python
    plan: free
    buildCommand: |
      echo "🔨 Starting DiamondFinder backend build..."
      python -m pip install --upgrade pip
      pip install -e .
      chmod +x vanilla_generator
      echo "🧪 Testing imports..."
      python -c "
import fastapi
import uvicorn
import pydantic
import requests
import json
import os
import logging
print('✅ All core imports successful!')
try:
    from server_api import app
    print('✅ Server API imported successfully!')
except ImportError as e:
    print(f'⚠️ Server API import warning: {e}')
print('🎉 Build completed successfully!')
"
    startCommand: python server_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
      - key: PIP_NO_CACHE_DIR
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "*.sh"
        - "requirements.txt"
        - "runtime.txt"
        - "enriched_servers.json"
        - "vanilla_generator" 