services:
  - type: web
    name: diamondfinder-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health
    autoDeploy: true 