services:
  - type: web
    name: diamondfinder-backend
    env: python
    plan: free
    buildCommand: |
      echo "🔨 Starting DiamondFinder backend build..."
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      chmod +x vanilla_generator
      echo "🧪 Testing imports and ore generation..."
      python -c "
import fastapi
import uvicorn
import pydantic
import requests
import json
import os
import logging
print('✅ All core imports successful!')
try:
    from server_api import app
    print('✅ Server API imported successfully!')
    from java_ore_generator import JavaOreFinderService
    service = JavaOreFinderService()
    result = service.find_ores(5522, 2, 3, '1.20', radius=1, ore_type='diamond')
    print(f'✅ Java ore generation working: Found {result.total_count} diamonds')
except ImportError as e:
    print(f'⚠️ Import warning: {e}')
except Exception as e:
    print(f'⚠️ Ore generation warning: {e}')
print('🎉 Build completed successfully!')
"
    startCommand: python -m uvicorn server_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PORT
        value: 8000
      - key: PIP_NO_CACHE_DIR
        value: 1
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "*.py"
        - "*.sh"
        - "requirements.txt"
        - "runtime.txt"
        - "enriched_servers.json"
        - "vanilla_generator" 